#pragma once

// from https://fontello.com/

#define ICON_STAR "\xee\xa0\x80"
#define ICON_EMPTY_STAR "\xee\xa0\x81"
#define ICON_IMAGE "\xee\xa0\x82"
#define ICON_FOLDER "\xee\xa0\x83"
#define ICON_BATTERY_25 "\xee\xa0\x84"
#define ICON_BATTERY_50 "\xee\xa0\x85"
#define ICON_BATTERY_75 "\xee\xa0\x86"
#define ICON_BATTERY_100 "\xee\xa0\x87"
#define ICON_BATTERY_CHARGE "\xee\xa0\x88"
#define ICON_OPTIONS "\xee\xa0\x89"
#define ICON_INFO "\xee\xa0\x8a"
#define ICON_SAVE "\xee\xa0\x8b"
#define ICON_HOME "\xee\xa0\x8c"
#define ICON_LINK "\xef\x82\x8e"
#define ICON_MENU "\xef\x83\x89"
#define ICON_GAMEPAD "\xef\x84\x9b"
#define ICON_ROCKET "\xef\x84\xb5"
#define ICON_SLIDER "\xef\x87\x9e"
#define ICON_PS "\xee\x80\x80"
#define ICON_OFF "\xef\x88\x84"
#define ICON_ON "\xef\x88\x85"

#define ICON_STAR_SPACE ICON_STAR " "
#define ICON_EMPTY_STAR_SPACE ICON_EMPTY_STAR " "
#define ICON_IMAGE_SPACE ICON_IMAGE " "
#define ICON_FOLDER_SPACE ICON_FOLDER " "
#define ICON_BATTERY_25_SPACE ICON_BATTERY_25 " "
#define ICON_BATTERY_50_SPACE ICON_BATTERY_50 " "
#define ICON_BATTERY_75_SPACE ICON_BATTERY_75 " "
#define ICON_BATTERY_100_SPACE ICON_BATTERY_100 " "
#define ICON_BATTERY_CHARGE_SPACE ICON_BATTERY_CHARGE " "
#define ICON_OPTIONS_SPACE ICON_OPTIONS " "
#define ICON_INFO_SPACE ICON_INFO " "
#define ICON_SAVE_SPACE ICON_SAVE " "
#define ICON_HOME_SPACE ICON_HOME " "
#define ICON_LINK_SPACE ICON_LINK " "
#define ICON_MENU_SPACE ICON_MENU " "
#define ICON_GAMEPAD_SPACE ICON_GAMEPAD " "
#define ICON_ROCKET_SPACE ICON_ROCKET " "
#define ICON_SLIDER_SPACE ICON_SLIDER " "
#define ICON_PS_SPACE ICON_PS " "
#define ICON_OFF_SPACE ICON_OFF " "
#define ICON_ON_SPACE ICON_ON " "
