CORES = {
    'ARC': ('fba_lite', 'fbalpha2012', 'fbneo', 'mame2000', 'mame2003', 'mame2003_plus'),
    'GBA': ('gpsp', 'mgba', 'vba_next'),
    'GBC': ('gambatte',),
    'MD': ('genesis_plus_gx', 'genesis_plus_gx_wide', 'picodrive'),
    'NES': ('fceumm', 'nestopia'),
    'NGP': ('mednafen_ngp',),
    'PCE': ('mednafen_pce_fast', 'mednafen_supergrafx'),
    'PS1': ('pcsx_rearmed',),
    'SNES': ('snes9x2002', 'snes9x2005', 'snes9x2010'),
    'WSC': ('mednafen_wswan',),
    'ATARI': ('stella2014', 'prosystem', 'atari800'),
    'DOS': ('dosbox_pure', 'dosbox_svn'),
}

NAMES = {
    'atari800': 'Atari 800',
    'dosbox_pure': 'DOSBox Pure',
    'dosbox_svn': 'DOSBox SVN',
    'fbalpha2012': 'FinalBurn Alpha 2012',
    'fba_lite': 'FinalBurn Alpha Lite',
    'fbneo': 'FinalBurn Neo',
    'fceumm': 'FCEUmm',
    'gambatte': 'Gambatte',
    'genesis_plus_gx': 'Genesis Plus GX',
    'genesis_plus_gx_wide': 'Genesis Plus GX Wide',
    'gpsp': 'gpSP',
    'mame2000': 'MAME 2000',
    'mame2003': 'MAME 2003',
    'mame2003_plus': 'MAME 2003 Plus',
    'mednafen_ngp': 'Mednafen NeoPop',
    'mednafen_pce_fast': 'Mednafen PCE Fast',
    'mednafen_supergrafx': 'Mednafen PCE SuperGrafx',
    'mednafen_wswan': 'Mednafen Wswan',
    'mgba': 'mGBA',
    'nestopia': 'Nestopia',
    'pcsx_rearmed': 'PCSX ReARMed',
    'picodrive': 'PicoDrive',
    'prosystem': 'ProSystem',
    'snes9x2002': 'Snes9x 2002',
    'snes9x2005': 'Snes9x 2005',
    'snes9x2010': 'Snes9x 2010',
    'stella2014': 'Stella 2014',
    'vba_next': 'VBA Next',
}
