#pragma once

#define AUDIO_OUTPUT_COUNT (256)
#define AUDIO_STEREO 1
#define AUDIO_OUTPUT_BLOCK_SIZE (AUDIO_OUTPUT_COUNT << AUDIO_STEREO)
#define AUDIO_OUTPUT_BUF_SIZE (AUDIO_OUTPUT_BLOCK_SIZE << 3)
#define AUDIO_DEFAULT_SAMPLE_RATE 48000
#define SAMPLE_RATE_NEGLECT 50
